# Estudo sobre a base do jogo Jokenpower

In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv('attacks_pattern.csv')
df

timestamp  time_since_start damaged_player attack_type  \
0   2023-03-18 22:18:58.246426              3453           Main        Rock   
1   2023-03-18 22:18:58.361588              3569          Enemy        Rock   
2   2023-03-18 22:18:59.762810              4970           Main       Paper   
3   2023-03-18 22:19:00.747199              5954          Enemy    Scissors   
4   2023-03-18 22:19:01.854446              7061           Main        Rock   
5   2023-03-18 22:19:02.575044              7782          Enemy       Paper   
6   2023-03-18 22:19:03.359242              8566           Main       Paper   
7   2023-03-18 22:19:05.045920             10253          Enemy        Rock   
8   2023-03-18 22:19:06.062385             11269          Enemy        Rock   
9   2023-03-18 22:19:06.833887             12040          Enemy        Rock   
10  2023-03-18 22:19:07.862736             13062          Enemy        Rock   
11  2023-03-18 22:19:08.644172             13852          Enemy        Rock   
12  2023-03-18 22:19:09.674454             14881          Enemy        Rock   
13  2023-03-18 22:19:10.575350             15782           Main       Paper   
14  2023-03-18 22:19:11.835821             17043          Enemy    Scissors   
15  2023-03-18 22:19:12.374495             17581           Main    Scissors   
16  2023-03-18 22:26:58.183300              3374          Enemy        Rock   
17  2023-03-18 22:26:58.594487              3785           Main        Rock   
18  2023-03-18 22:26:59.346769              4537          Enemy       Paper   
19  2023-03-18 22:27:00.267225              5458          Enemy        Rock   
20  2023-03-18 22:27:01.299129              6490          Enemy        Rock   
21  2023-03-18 22:27:02.886613              8077           Main        Rock   
22  2023-03-18 22:27:03.231267              8422          Enemy       Paper   
23  2023-03-18 22:27:04.698223              9889           Main       Paper   
24  2023-03-18 22:27:05.434063             10625          Enemy        Rock   
25  2023-03-18 22:27:06.630059             11821          Enemy       Paper   
26  2023-03-18 22:27:06.847124             12033           Main       Paper   
27  2023-03-18 22:27:07.885174             13076          Enemy    Scissors   
28  2023-03-18 22:27:08.980895             14172           Main       Paper   
29  2023-03-18 22:27:09.355238             14546          Enemy    Scissors   
30  2023-03-18 22:27:11.408531             16599           Main        Rock   
31  2023-03-18 22:27:11.753330             16944          Enemy    Scissors   
32  2023-03-18 22:27:13.253347             18444           Main    Scissors   
33  2023-03-18 22:27:13.715777             18907          Enemy       Paper   
34  2023-03-18 22:27:15.223707             20414          Enemy        Rock   
35  2023-03-18 22:27:15.684966             20876           Main        Rock   
36  2023-03-18 22:27:16.180909             21370          Enemy    Scissors   
37  2023-03-18 22:27:17.520162             22712           Main       Paper   

    damage  is_counter_attack  
0       10              False  
1       10              False  
2        1              False  
3        3              False  
4       10              False  
5        1              False  
6        1              False  
7       20               True  
8       10              False  
9       20               True  
10      10              False  
11      20               True  
12      10              False  
13       1              False  
14       3              False  
15       3              False  
16      10              False  
17      10              False  
18       1              False  
19      20               True  
20      10              False  
21      10              False  
22       1              False  
23       1              False  
24      10              False  
25       1              False  
26       1              False  
27       3              False  
28       1 

## Tratamento de dados

In [3]:
# Parsear string timestamp para Tipo Timestamp do pandas
df['timestamp'] = pd.to_datetime(df['timestamp'], infer_datetime_format=True)

In [4]:
# Criar campo com diferença de tempo entre ataques
df['time_diff'] = df['timestamp'].diff().dt.total_seconds()

In [5]:
# Definir início de partida: quando próximo time_since_start for menor que anterior
df.loc[df['time_since_start'].diff() < 0, 'time_diff'] = np.nan

In [6]:
# Deletar NaN da tabela
df.dropna(inplace=True)

In [7]:
# Normalizando diferença de tempo entre ataques
df['label_time_diff'] = df['time_diff'].apply(lambda x: int(x*10))

In [8]:
# Normalizando valores qualitativos para quantitativos

def get_norm_attack_type(atk: str):
    result = 99
    if atk == 'Rock':
        result = 0
    elif atk == 'Paper':
        result = 1
    elif atk == 'Scissors':
        result = 2
    return result

df['label_attack_type'] = df['attack_type'].apply(get_norm_attack_type)

In [9]:
df

timestamp  time_since_start damaged_player attack_type  \
1  2023-03-18 22:18:58.361588              3569          Enemy        Rock   
2  2023-03-18 22:18:59.762810              4970           Main       Paper   
3  2023-03-18 22:19:00.747199              5954          Enemy    Scissors   
4  2023-03-18 22:19:01.854446              7061           Main        Rock   
5  2023-03-18 22:19:02.575044              7782          Enemy       Paper   
6  2023-03-18 22:19:03.359242              8566           Main       Paper   
7  2023-03-18 22:19:05.045920             10253          Enemy        Rock   
8  2023-03-18 22:19:06.062385             11269          Enemy        Rock   
9  2023-03-18 22:19:06.833887             12040          Enemy        Rock   
10 2023-03-18 22:19:07.862736             13062          Enemy        Rock   
11 2023-03-18 22:19:08.644172             13852          Enemy        Rock   
12 2023-03-18 22:19:09.674454             14881          Enemy        Rock   
13 2023-03-18 22:19:10.575350             15782           Main       Paper   
14 2023-03-18 22:19:11.835821             17043          Enemy    Scissors   
15 2023-03-18 22:19:12.374495             17581           Main    Scissors   
17 2023-03-18 22:26:58.594487              3785           Main        Rock   
18 2023-03-18 22:26:59.346769              4537          Enemy       Paper   
19 2023-03-18 22:27:00.267225              5458          Enemy        Rock   
20 2023-03-18 22:27:01.299129              6490          Enemy        Rock   
21 2023-03-18 22:27:02.886613              8077           Main        Rock   
22 2023-03-18 22:27:03.231267              8422          Enemy       Paper   
23 2023-03-18 22:27:04.698223              9889           Main       Paper   
24 2023-03-18 22:27:05.434063             10625          Enemy        Rock   
25 2023-03-18 22:27:06.630059             11821          Enemy       Paper   
26 2023-03-18 22:27:06.847124             12033           Main       Paper   
27 2023-03-18 22:27:07.885174             13076          Enemy    Scissors   
28 2023-03-18 22:27:08.980895             14172           Main       Paper   
29 2023-03-18 22:27:09.355238             14546          Enemy    Scissors   
30 2023-03-18 22:27:11.408531             16599           Main        Rock   
31 2023-03-18 22:27:11.753330             16944          Enemy    Scissors   
32 2023-03-18 22:27:13.253347             18444           Main    Scissors   
33 2023-03-18 22:27:13.715777             18907          Enemy       Paper   
34 2023-03-18 22:27:15.223707             20414          Enemy        Rock   
35 2023-03-18 22:27:15.684966             20876           Main        Rock   
36 2023-03-18 22:27:16.180909             21370          Enemy    Scissors   
37 2023-03-18 22:27:17.520162             22712           Main       Paper   

    damage  is_counter_attack  time_diff  label_time_diff  label_attack_type  
1       10              False   0.115162                1                  0  
2        1              False   1.401222               14                  1  
3        3              False   0.984389                9                  2  
4       10              False   1.107247               11                  0  
5        1              False   0.720598                7                  1  
6        1              False   0.784198                7                  1  
7       20               True   1.686678               16                  0  
8       10              False   1.016465               10                  0  
9       20               True   0.771502                7                  0  
10      10              False   1.028849               10                  0  
11      20               True   0.781436                7                  0  
12      10              False   1.030282               10                  0  
13       1              False   0.900896                9                  1  
14       3              Fal

## Scikit Learn

In [10]:
# Pegar apenas danos ao inimigo = Apenas do player
df_only_player = df.loc[df['damaged_player'] == 'Enemy']

In [11]:
# Filtrar apenas colunas necessárias para fator X
x_chance_contra_ataque = df_only_player.loc[:, ['label_attack_type', 'label_time_diff']].values
x_chance_contra_ataque

array([[ 0,  1],
       [ 2,  9],
       [ 1,  7],
       [ 0, 16],
       [ 0, 10],
       [ 0,  7],
       [ 0, 10],
       [ 0,  7],
       [ 0, 10],
       [ 2, 12],
       [ 1,  7],
       [ 0,  9],
       [ 0, 10],
       [ 1,  3],
       [ 0,  7],
       [ 1, 11],
       [ 2, 10],
       [ 2,  3],
       [ 2,  3],
       [ 1,  4],
       [ 0, 15],
       [ 2,  4]])

In [12]:
# Filtrar apenas coluna necessária para fator Y
y_chance_contra_ataque = df_only_player.loc[:, 'is_counter_attack'].values
y_chance_contra_ataque

array([False, False, False,  True, False,  True, False,  True, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False])

### Normalização de valores qualitativos para quantitativos

In [13]:
# Normalização deve ser feita para o modelo GaussianNB aceitar como input

# from sklearn.preprocessing import LabelEncoder
# label_encoder_attack_type = LabelEncoder()
# x_chance_contra_ataque[:,0] = label_encoder_attack_type.fit_transform(x_chance_contra_ataque[:,0])

### Treinamento do modelo com algoritmo Naive Bayes

In [14]:
from sklearn.naive_bayes import GaussianNB

In [15]:
naive_chance_contra_ataque = GaussianNB()
naive_chance_contra_ataque.fit(x_chance_contra_ataque, y_chance_contra_ataque)

GaussianNB()

### Previsão

In [16]:
# utilizando o modelo: de acordo com o input de teste, prever se irá contra-atacar
# [[0, 7]] -> [['Rock', time_diff]]
previsao = naive_chance_contra_ataque.predict([[0, 7]])
previsao

array([ True])

# Gráficos de Comparação

In [18]:
# Pegar apenas danos ao inimigo = Apenas do player
df_only_player 

timestamp  time_since_start damaged_player attack_type  \
1  2023-03-18 22:18:58.361588              3569          Enemy        Rock   
3  2023-03-18 22:19:00.747199              5954          Enemy    Scissors   
5  2023-03-18 22:19:02.575044              7782          Enemy       Paper   
7  2023-03-18 22:19:05.045920             10253          Enemy        Rock   
8  2023-03-18 22:19:06.062385             11269          Enemy        Rock   
9  2023-03-18 22:19:06.833887             12040          Enemy        Rock   
10 2023-03-18 22:19:07.862736             13062          Enemy        Rock   
11 2023-03-18 22:19:08.644172             13852          Enemy        Rock   
12 2023-03-18 22:19:09.674454             14881          Enemy        Rock   
14 2023-03-18 22:19:11.835821             17043          Enemy    Scissors   
18 2023-03-18 22:26:59.346769              4537          Enemy       Paper   
19 2023-03-18 22:27:00.267225              5458          Enemy        Rock   
20 2023-03-18 22:27:01.299129              6490          Enemy        Rock   
22 2023-03-18 22:27:03.231267              8422          Enemy       Paper   
24 2023-03-18 22:27:05.434063             10625          Enemy        Rock   
25 2023-03-18 22:27:06.630059             11821          Enemy       Paper   
27 2023-03-18 22:27:07.885174             13076          Enemy    Scissors   
29 2023-03-18 22:27:09.355238             14546          Enemy    Scissors   
31 2023-03-18 22:27:11.753330             16944          Enemy    Scissors   
33 2023-03-18 22:27:13.715777             18907          Enemy       Paper   
34 2023-03-18 22:27:15.223707             20414          Enemy        Rock   
36 2023-03-18 22:27:16.180909             21370          Enemy    Scissors   

    damage  is_counter_attack  time_diff  label_time_diff  label_attack_type  
1       10              False   0.115162                1                  0  
3        3              False   0.984389                9                  2  
5        1              False   0.720598                7                  1  
7       20               True   1.686678               16                  0  
8       10              False   1.016465               10                  0  
9       20               True   0.771502                7                  0  
10      10              False   1.028849               10                  0  
11      20               True   0.781436                7                  0  
12      10              False   1.030282               10                  0  
14       3              False   1.260471               12                  2  
18       1              False   0.752282                7                  1  
19      20               True   0.920456                9                  0  
20      10              False   1.031904               10                  0  
22       1              False   0.344654                3                  1  
24      10              False   0.735840                7                  0  
25       1              False   1.195996               11                  1  
27       3              False   1.038050               10                  2  
29       3              False   0.374343                3                  2  
31       3              False   0.344799                3                  2  
33       1              False   0.462430                4                  1  
34      10              False   1.507930               15                  0  
36       3              False   0.495943                4                  2